### ISSUE TITLE
建议自己使用时把模板文件内容清空，减小导出大小

### ISSUE THREAD

**Issue by realysy** [Achuan-2/pandoc_word_template#4]
我导出时发现

- 模板文件本身516kb
- 就算笔记内容很少，就几个字，导出之后的docx也有500kb
- 而如果把模板文件ctrl+A后把内容全部删除，再导出，则只有18kb左右，模板仍然生效

我的环境：
* ubuntu 20.04
* pandoc 2.5
* 思源笔记 3.1.9

**Comment by Achuan-2** [comment]
谢谢反馈，不过模板文件内容我暂时不打算清空，不然不方便查看，可以自己使用时把模板文件内容清空，我在readme添加下这个提示

**Comment by realysy** [comment]
确实，我本地也是留了一份未清空的方便查看

**Comment by wangfeng35** [comment]
发现一个非模板的而是pandoc新版的问题，这里提醒一下。
pandoc3.2以上的版本转docx时候，标题样式可能不生效。讨论在下面：
https://github.com/jgm/pandoc/issues/10282

**Comment by Achuan-2** [comment]
> 发现一个非模板的而是pandoc新版的问题，这里提醒一下。 pandoc3.2以上的版本转docx时候，标题样式可能不生效。讨论在下面： [jgm/pandoc#10282](https://github.com/jgm/pandoc/issues/10282)

好的，谢谢提醒，我目前用的 v3.1.3
